spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hadiz
    username: doeun
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace`

server:
  port: 8081



